version: '3'
services:
    web:
        build: ./web_application
        volumes:
            - ./web_application:/app
            - ./blueapron.crt:/etc/demo/ssl/blueapron.crt
            - ./blueapron.key:/etc/demo/ssl/blueapron.key
        command:
            - app.py

        environment: 
            FLASK_ENV: development
        restart: on-failure
    nginx:
        image: nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx/demo.conf:/etc/nginx/sites-enabled/demo.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./blueapron.crt:/etc/nginx/ssl/blueapron.crt
            - ./blueapron.key:/etc/nginx/ssl/blueapron.key

        


